name: temple
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  intl: ^0.16.1
  flutter_native_splash: ^0.1.9
  flutter_advanced_networkimage: ^0.7.0
  google_maps_flutter: ^0.5.32
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Yomogi
      fonts:
        - asset: assets/fonts/yomogifont.ttf

  assets:
    - assets/image/

flutter_native_splash:
  image: "assets/image/cover.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/ic_launcher.png"

adaptive_icon_background: "#2e2e2e"
adaptive_icon_foreground: "assets/images/ic_launcher.png"
